# Generated by Django 3.1.1 on 2020-09-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('tempo', models.IntegerField()),
                ('notes', models.CharField(max_length=100)),
                ('bassDrumNotes', models.CharField(max_length=100)),
                ('cymbalNotes', models.CharField(max_length=100)),
                ('snareNotes', models.CharField(max_length=100)),
            ],
        ),
    ]
